# Generated by Django 3.2.3 on 2021-05-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210517_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='description',
        ),
    ]
